### ISSUE TITLE
Suggestion: Declare a color for light mode and another one for dark mode for categories

### ISSUE THREAD

**Issue by GerardPaligot** [HugoGresse/OpenPlanner#100]
To be able to handle correctly the color contrast in our frontend applications, it could be great to declare a light and dark color (potentially optional) for every category declared in the settings page.

![image](https://github.com/HugoGresse/OpenPlanner/assets/1913901/23d48b73-6c4b-46ae-9da9-8e81ac424df5)

**Comment by HugoGresse** [comment]
We could have a "color2" which would be used for whatever reason by the user?

**Comment by GerardPaligot** [comment]
Totally
