### ISSUE TITLE
Proposal: Random color for new category

### ISSUE THREAD

**Issue by xavier-calland** [HugoGresse/OpenPlanner#51]
When adding a new category or when importing from Conferance-Hall, it would be great to have different colors.

Current behavior seem to be :
- new category from "+" button in "Event settings" : color is back
- all categories from Conferall-Hall : color is `DEFAULT_SESSION_CARD_BACKGROUND_COLOR`

Proposal
When creating a new category, generate and assign a color to the category

**Comment by HugoGresse** [comment]
Good idea, seems pretty straight forward todo

**Comment by HugoGresse** [comment]
Done and deployed!
