### ISSUE TITLE
Suggestion: Add custom slots in the schedule

### ISSUE THREAD

**Issue by GerardPaligot** [HugoGresse/OpenPlanner#96]
Be able to add custom slots in the schedule like:

* Break
* Lunch time
* Registration
* Party
* Etc

**Comment by HugoGresse** [comment]
Already possible! You can add "session" for lunch, break, etc. 
<img width="522" alt="image" src="https://github.com/HugoGresse/OpenPlanner/assets/662377/7abe88ff-291b-4a5c-b337-d9d95d74c9c8">
