### ISSUE TITLE
Bug: Can't upload a picture for a speaker

### ISSUE THREAD

**Issue by GerardPaligot** [HugoGresse/OpenPlanner#97]
**Describe the bug**
If I would like to add a custom image from the speaker profile in OpenPlanner
When I click on "UPLOAD IMAGE"
Then nothing happens

![Capture d’écran 2024-04-21 à 20 58 21](https://github.com/HugoGresse/OpenPlanner/assets/1913901/1a9185b2-3a01-4aee-ba17-f3e05007f993)

**Expected behavior**
A new public URL is created for this speaker and the profile picture is updated with this new image

**Comment by HugoGresse** [comment]
Could you specify your browser details? Also, any specific plugins installed? Maybe trying in a private window and checking the console log could help diagnosed this.

**Comment by GerardPaligot** [comment]
Yes, I'm using Chrome Version 124.0.6367.61 (Build officiel) (arm64).
I've only "Beamy", "Chrome Remote Desktop" and "Google Docs hors connexion" installed as plugin.
And the console log just show nothing when I try to upload my image:

![Capture d’écran 2024-04-21 à 22 29 13](https://github.com/HugoGresse/OpenPlanner/assets/1913901/00d558e0-eddf-401b-a8ab-5f31e03b8c56)

**Comment by HugoGresse** [comment]
I cannot reproduce the issue on Chrome 124.0 arm64. 
My version does not contain Beamy, Chrome Remote Desktop and google docs. 

Did you try in a private window? Could you also try on another browser to see if it's browser related or within OpenPlanner?

**Comment by GerardPaligot** [comment]
Fixed by #98
